config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "requests#new"
  get "up" => "rails/health#show", as: :rails_health_check
  get "/profile", to: "pages#profile"

  resources :requests, only: [ :show, :new, :create, :edit, :update ] do
  member do
    patch :archive
  end
end
  resources :activities, only: [ :update ]
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :request

  validates :location, presence: true
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  def gmaps_params
    self.location.split(',').join('%2C').split(' ').join('+')
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  has_many :activities
  validates :duration, :lat, :lon, presence: true
  validates :duration, numericality: { only_integer: true, greater_than: 0 }

  reverse_geocoded_by :lat, :lon
  after_validation :reverse_geocode

  def create_activities
    response["activities"].each do |activity|
      loc = activity["location"]
      loc = "Quartier du Panier, 13002 Marseille, France" if activity["location"].match?(/\b[Pp]anier\b.*\b[Mm]arseille\b|\b[Mm]arseille\b.*\b[Pp]anier\b/)
      # loc = activity["location"] if activity["location"].split(",").count == 3
      loc = activity["location"].split(",").drop(1).join(",") if activity["location"].split(",").count == 4
      # loc = activity["location"].split(",")[2..3].unshift(activity["location"].split(",").first).join(",") if activity["location"].split(",").count == 4
      acti = Activity.new(name: activity["title"], description: activity["description"], location: loc)
      acti.request = self
      acti.save!
    end
  end

  def format_duration
     hours = duration / 60
     minutes = (duration % 60).to_s.rjust(2, "0")
     "#{hours}h #{minutes} min to kill at:"
  end

  # def postion
  #   result = request.safe_location
  # end

  private

  def response
    # location = Geocoder.address([ lat, lon ])
    client = OpenAI::Client.new
    chatgpt_response = client.chat(parameters: {
      model: "gpt-4o",
      response_format: { type: "json_object" },
      messages: [ { role: "user", content: "We are #{Date.today} and the time is #{Time.now.strftime("%H:%M")}. Suggest 5 seasonal activities around #{address} that can fill my #{duration} minutes time span. Respond in JSON format. Each activity should include: title, description and location. Location has to be an address" } ],
      temperature: 0.2
    })

    json_content = chatgpt_response.dig("choices", 0, "message", "content")
    parsed_content = JSON.parse(json_content)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :requests
  has_many :activities, through: :requests

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  def update
    @activity = Activity.find(params[:id])
    @activity.update!(done: true)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # allow_browser versions: :modern
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def profile
    @user = current_user
    @requests = Request.where(user_id: @user.id).order(created_at: :desc)
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def new
    @request = Request.new
  end

  def create
    @request = Request.new(duration: (request_params[:hours].to_i * 60 + request_params[:minutes].to_i), lat: request_params[:latitude], lon: request_params[:longitude])
    if user_signed_in?
      @request.user = current_user
    else
      @request.user = User.find_by(email: "default.user@watodo.bug")
    end

    if @request.save
      AskaiJob.perform_now(@request)
      redirect_to request_path(@request)
    else
      flash[:alert] = "Location permission must be on and you have to set a time frame"
      render :new, status: :unprocessable_entity
    end
  end

  def show
    # @markers = []
    @request = Request.find(params[:id])
    @markers = @request.activities.map do |activity|
      {
        lat: activity.latitude,
        lng: activity.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { activity: activity }),
        type: "activity"
      }
    end

    if @request
      @markers << {
        lat: @request.lat,
        lon: @request.lon,
        info_window_html: render_to_string(partial: "info_window", locals: { activity: Activity.first }),
        type: "user"
      }
    end
  end
  def archive
    @request = Request.find(params[:id])
    @request.update(archived: true)  # Assure-toi d'avoir un attribut "archived" dans ta base de données
    redirect_to profile_path
  end

  def edit
  end

  def update
  end

  private

  def request_params
    params.require(:request).permit(:hours, :minutes, :latitude, :longitude)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Watodo" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= render 'shared/ios_pwa_links' %>

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="body-class">
    <%# <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/profile.html.erb
<div class="navbar-custom justify-content-between">
  <%= link_to destroy_user_session_path, data: {turbo_method: :delete}, class: "profile-link" do %>
    <i class="fa-solid fa-user-xmark profile-icon"></i>
  <% end %>

  <%= link_to root_path, class: "profile-link" do %>
    <i class="fa-solid fa-house profile-icon"></i>
  <% end %>
</div>
<div class="navbar-custom justify-content-between">
  <%= link_to destroy_user_session_path, data: {turbo_method: :delete}, class: "profile-link" do %>
    <i class="fa-solid fa-user-xmark profile-icon"></i>
  <% end %>

  <%= link_to root_path, class: "profile-link" do %>
    <i class="fa-solid fa-house profile-icon"></i>
  <% end %>
</div>

<div class="container container-a pt-5 pb-3">

  <h3 class="mb-4"> See your old Searches:</h3>
  <div class="row row-cols-1 row-cols-md-2 g-3">
    <% @requests.where(archived: false).each do |request| %>
      <div class="col">
        <div class="card-custom-b shadow-sm h-100 position-relative">

          <div class="card-body-y d-flex flex-column justify-content-between flex-fill p-3">
            <h6 class="card-title d-flex justify-content-between"><b><%= request.created_at.strftime(" %Y : %a %e %b ") %></b>
              <%= link_to  archive_request_path(request), data: { 'turbo-method': :patch}, class: "btn-archive" do %>
                <i class="fa-solid fa-xmark"></i>
              <% end %>
            </h6>
            <p class="card-text">
              <%= request.format_duration %><br>
              <b><%= request.address %> </b>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <h3 class="mt-5 mb-4">Activities you did:</h3>
  <div class="row row-cols-1 row-cols-md-2 g-3">
    <% @requests.where(archived: false).each do |request| %>
      <% request.activities.each do |activity| %>
        <% if activity.done %>
          <div class="col">
            <div class="card-custom-c shadow-sm h-100">
              <div class="card-body-y d-flex flex-column justify-content-between flex-fill p-3">
                <h6 class="card-title"><b><%= activity.created_at.strftime(" %Y : %a %e %b ") %></b></h6>
                <h5 class="card-subtitle mb-2"> <%= activity.name %></h5>
                <p class="card-text">
                  <b>at:</b> <%= activity.location %>
                </p>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/requests/_activity.html.erb
<div class="col">
  <div class="card-custom shadow-sm h-100 " >
    <div class="card-body d-flex flex-column justify-content-between p-3 ">


        <h2 class="card-title "><%= activity.name %></h2>

        <p class="card-text mb-2">
          <%= activity.description %>
        </p>

      <p data-controller="doitbutton" data-doitbutton-gmaps-value=<%= activity.gmaps_params %> class="d-flex justify-content-end mt-2 mb-0">
        <%= link_to "Do it!", activity_path(activity), data: { 'turbo-method': :patch, action: "doitbutton#send", doitbutton_target: "link" }, class: "custom-btn"%>
      </p>
    </div>
  </div>
</div>

app/views/requests/_info_window.html.erb
  <div class="card-header text-center text-black rounded">
    <h2 class="h5 m-0">
         <%= activity.name %>

      </h2>
  </div>


  <div class="card-body-1 d-flex flex-column justify-content-between">
    <p class="card-text text-muted mb-2">
      <i class="bi bi-geo-alt-fill text-danger"></i> <%= activity.location %>
    </p>
  </div>
<p data-controller=" doitbutton" data-doitbutton-gmaps-value=<%= activity.gmaps_params %> class="d-flex justify-content-end  mb-0" >

   <%= link_to  activity_path(activity), data: { 'turbo-method': :patch, action: "doitbutton#send", doitbutton_target: "link" }, class: "custom-btn" do %>
   <i class="fa-solid fa-location-arrow"></i>
  <% end %>
</p>

app/views/requests/new.html.erb
<div class="banner-watodo"  data-controller="loading" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)), url('<%= image_path("8ce5289c-75da-4b14-9c63-2a623d1cdaef.jpg") %>');">
  <div class="overlay" data-loading-target="overlay"></div>
  <div class="navbar-custom d-flex justify-content-between">
    <% if user_signed_in? %>
      <%= link_to profile_path class: "profile-link" do %>
        <i class="fa-solid fa-user profile-icon"></i>
      <% end %>
    <% else %>
      <%= link_to new_user_session_path, class: "profile-link" do %>
        <i class="fa-solid fa-user profile-icon"></i>
      <% end %>
    <% end %>
  </div>
  <div class="container container-home">
      <div class="title-container">
      <h1 class="animated-title">
        <span>W</span>
        <span>A</span>
        <span>T</span>
        <span>O</span>
        <span>D</span>
        <span>O</span>
      </h1>
      <h2 class="slogan mt-4 pt-4">
        <p>Discover</p>
        <p>your surroundings</p>
      </h2>
    </div>
    <img class="d-none" data-loading-target="loading" src="https://cdn.pixabay.com/animation/2022/10/11/03/16/03-16-39-160_512.gif" alt="" style="width: 100px; height: 100px; margin-top: 5vh; z-index:100; position: relative;">
  </div>

  <div class="form-overlay">
    <%= form_with model: @request, url: requests_path, html: { class: "form-inline" }, data: { controller: "user-coordinates"} do |form| %>
    <div class="my-block" style="display:flex; flex-direction: column; padding: 0px 10px;">
      <%= form.submit "Search", class: "btn-search d-flex justify-content-center align-items-center", data: { action: "click->loading#loading"} %>
      <div class="form-main">
        <div class="time-inputs">
          <%= form.number_field :hours, step: 1, min: 0, placeholder: "hours...", class: "form-control time-field" %>
          <span>:</span>
          <%= form.number_field :minutes, step: 1, min: 0, max: 59, placeholder: "minutes...", class: "form-control time-field" %>
        </div>
      </div>
    </div>
      <%= form.hidden_field :latitude, data: { user_coordinates_target: "latitude" } %>
      <%= form.hidden_field :longitude, data: {user_coordinates_target: "longitude" } %>
    <% end %>
  </div>
</div>

app/views/requests/show.html.erb
<div data-controller="scrolling">
<div class="navbar-custom justify-content-between">
  <%= link_to root_path, class: "profile-link" do %>
    <i class="fa-solid fa-house profile-icon"></i>
  <% end %>
  <div class="d-flex">
    <i class="fa-solid fa-list-ul profile-icon me-2"
      data-action="click->scrolling#scrollToTop"></i>

    <i class="fa-solid fa-map-location-dot profile-icon ms-2"
      data-action="click->scrolling#scrollToBottom"></i>
  </div>
    <i class="fa-solid fa-magnifying-glass-plus profile-icon"></i>
</div>

<div class="container container-purple pt-5" data-scrolling-target="page">
  <div class="row row-cols-1 row-cols-md-2 g-1 mb-3">
    <% @request.activities.each_with_index do |activity, index| %>
      <div class="col card-animation">
        <div class="card-custom shadow-sm h-100 " >
          <div class="card-body d-flex flex-column justify-content-between p-3 ">
              <h2 class="card-title ">
                    <%= "#{index + 1}. #{activity.name}" %>
              </h2>

              <p class="card-text mb-2">
                <%= activity.description %>
              </p>

            <p data-controller="doitbutton" data-doitbutton-gmaps-value=<%= activity.gmaps_params %> class="d-flex justify-content-end mt-2 mb-0">
              <%= link_to "Do it!", activity_path(activity), data: { 'turbo-method': :patch, action: "doitbutton#send", doitbutton_target: "link" }, class: "custom-btn"%>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="map my-2"
    style="width: 100%; height: 90vh; margin: 0 auto;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="flash flash-success alert alert-dismissible fade show" role="alert">
    <span><strong>Yay!</strong> 🎉 <%= notice %> </span>
    <a style="margin-left: 3px" data-bs-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

<% if alert %>
  <div class="flash flash-warning alert alert-dismissible fade show" role="alert">
    <span><strong>Mmh</strong> 🤔 <%= alert %> </span>
    <a style="margin-left: 3px" data-bs-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/profile", class: "navbar-brand" do %>
      <i class="fa-solid fa-user"></i>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>